<a href="https://colab.research.google.com/github/saini128/ML_assignments/blob/main/Assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
customers=pd.read_csv('AWCustomers.csv')
print(customers.head())

   CustomerID Title FirstName MiddleName  LastName Suffix  \
0       21173   NaN      Chad          C      Yuan    NaN
1       13249   NaN      Ryan        NaN     Perry    NaN
2       29350   NaN     Julia        NaN  Thompson    NaN
3       13503   NaN  Theodore        NaN     Gomez    NaN
4       22803   NaN  Marshall          J      Shan    NaN

             AddressLine1 AddressLine2         City    StateProvinceName  ...  \
0      7090 C. Mount Hood          NaN   Wollongong      New South Wales  ...
1     3651 Willow Lake Rd          NaN      Shawnee     British Columbia  ...
2  1774 Tice Valley Blvd.          NaN  West Covina           California  ...
3         2103 Baldwin Dr          NaN    Liverpool              England  ...
4         Am Gallberg 234          NaN        Werne  Nordrhein-Westfalen  ...

         Education      Occupation Gender MaritalStatus HomeOwnerFlag  \
0        Bachelors        Clerical      M             M             1
1  Partial College        Clerical      M             M             1
2        Bachelors        Clerical      F             S             0
3  Partial College  Skilled Manual      M             M             1
4  Partial College  Skilled Manual      M             S             1

  NumberCarsOwned NumberChildrenAtHome TotalChildren  YearlyIncome  \
0               3                    0             1         81916
1               2                    1             2         81076
2               3                    0             0         86387
3               2                    1             2         61481
4               1                    0             0         51804

   LastUpdated
0   2017-03-06
1   2017-03-06
2   2017-03-06
3   2017-03-06
4   2017-03-06

[5 rows x 24 columns]

In [2]:
sales=pd.read_csv('AWSales.csv')
print(sales.head())

   CustomerID  BikeBuyer  AvgMonthSpend
0       21173          1          50.97
1       13249          1          53.11
2       29350          1          54.08
3       13503          1          56.93
4       22803          1          55.41

Columns to drop in AWCustomers for analysis of data: Title, FirstName MiddleName, LastName, Suffix, Address, Education, Occupation, Gender, MaritalStatus, Home

In [4]:
selected_columns=['CustomerID','HomeOwnerFlag','NumberCarsOwned','NumberChildrenAtHome','TotalChildren','YearlyIncome']

In [5]:
customers_new=customers[selected_columns]
customers_new.head()

,CustomerID,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome
0,21173,1,3,0,1,81916
1,13249,1,2,1,2,81076
2,29350,0,3,0,0,86387
3,13503,1,2,1,2,61481
4,22803,1,1,0,0,51804